# Generated by Django 5.2.12 on 2026-05-14 00:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _fill_public_report_uuids(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    for d in Device.objects.all():
        if d.public_report_uuid is None:
            d.public_report_uuid = uuid.uuid4()
            d.save(update_fields=['public_report_uuid'])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_vendor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['warranty_end_date'], name='devices_dev_warrant_c1f31c_idx'),
        ),
        migrations.AddField(
            model_name='device',
            name='public_report_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(_fill_public_report_uuids, _noop_reverse),
        migrations.AlterField(
            model_name='device',
            name='public_report_uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='DeviceCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'checked_out_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_checkouts_held',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='device_checkouts_recorded',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='checkouts',
                        to='devices.device',
                    ),
                ),
            ],
            options={
                'db_table': 'devices_devicecheckout',
                'ordering': ['-checked_out_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicecheckout',
            index=models.Index(fields=['device', 'returned_at'], name='devices_dev_device__0b52cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicecheckout',
            constraint=models.UniqueConstraint(
                condition=models.Q(('returned_at__isnull', True)),
                fields=('device',),
                name='devices_devicecheckout_one_open_per_device',
            ),
        ),
    ]
