# Generated by Django 5.2.12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_warranty_checkout_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='public_report_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
