# Generated by Django 5.2.12 on 2026-05-26 23:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_public_report_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCheckoutPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_fee_enabled', models.BooleanField(default=True)),
                ('late_fee_per_day', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_grace_days', models.PositiveSmallIntegerField(default=0, help_text='Days after due date before late fees begin.')),
                ('late_fee_max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap per checkout; leave blank for no cap.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Device checkout policies',
                'db_table': 'devices_devicecheckoutpolicy',
            },
        ),
        migrations.CreateModel(
            name='DeviceFineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System types cannot be deleted (e.g. late return).')),
            ],
            options={
                'db_table': 'devices_devicefinetype',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('is_late_fee', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_fines_assessed', to=settings.AUTH_USER_MODEL)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='devices.devicecheckout')),
                ('fine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='devices.devicefinetype')),
            ],
            options={
                'db_table': 'devices_devicefine',
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['checkout', 'status'], name='devices_dev_checkou_cefd99_idx'), models.Index(fields=['status', 'assessed_at'], name='devices_dev_status_bdd852_idx')],
            },
        ),
    ]
