# Generated by Django 5.2.12 on 2026-05-20 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('ticket_category', 'Ticket category'), ('priority_level', 'Priority level'), ('ticket', 'Ticket')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_label', models.CharField(max_length=255)),
                ('field_name', models.CharField(blank=True, max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='tickets.ticket')),
            ],
            options={
                'db_table': 'core_adminauditentry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'object_id'], name='core_admina_entity__f3c9dc_idx'), models.Index(fields=['actor', 'created_at'], name='core_admina_actor_i_425141_idx'), models.Index(fields=['ticket', 'created_at'], name='core_admina_ticket__fdcdd4_idx'), models.Index(fields=['created_at'], name='core_admina_created_ba8c51_idx')],
            },
        ),
    ]
