# Generated by Django 5.2.12 on 2026-05-20 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_audit_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditentry',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adminauditentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminauditentry',
            name='entity_type',
            field=models.CharField(choices=[('user', 'User'), ('auth', 'Authentication'), ('ticket_category', 'Ticket category'), ('priority_level', 'Priority level'), ('ticket', 'Ticket')], max_length=20),
        ),
    ]
