from django.urls import path

from .settings_views import (
    CannedResponseCreateView,
    CannedResponseDeleteView,
    CannedResponseListView,
    CannedResponseUpdateView,
    PriorityLevelCreateView,
    PriorityLevelDeleteView,
    PriorityLevelListView,
    PriorityLevelUpdateView,
    TicketCategoryCreateView,
    TicketCategoryDeleteView,
    TicketCategoryListView,
    TicketCategoryUpdateView,
    TicketSettingsHubView,
)
from .views import (
    SavedTicketFilterCreateView,
    SavedTicketFilterDeleteView,
    SavedTicketFilterSetDefaultView,
    TicketAdminUpdateView,
    TicketAssignView,
    TicketAttachmentDownloadView,
    TicketCommentAddView,
    TicketCreateView,
    TicketDetailView,
    TicketExportCsvView,
    TicketListView,
    TicketRelationAddView,
    TicketRelationRemoveView,
)

app_name = 'tickets'

urlpatterns = [
    path('settings/', TicketSettingsHubView.as_view(), name='settings_hub'),
    path('settings/categories/', TicketCategoryListView.as_view(), name='category_list'),
    path('settings/categories/new/', TicketCategoryCreateView.as_view(), name='category_create'),
    path('settings/categories/<int:pk>/edit/', TicketCategoryUpdateView.as_view(), name='category_edit'),
    path('settings/categories/<int:pk>/delete/', TicketCategoryDeleteView.as_view(), name='category_delete'),
    path('settings/priorities/', PriorityLevelListView.as_view(), name='priority_list'),
    path('settings/priorities/new/', PriorityLevelCreateView.as_view(), name='priority_create'),
    path('settings/priorities/<int:pk>/edit/', PriorityLevelUpdateView.as_view(), name='priority_edit'),
    path('settings/priorities/<int:pk>/delete/', PriorityLevelDeleteView.as_view(), name='priority_delete'),
    path('settings/canned/', CannedResponseListView.as_view(), name='canned_list'),
    path('settings/canned/new/', CannedResponseCreateView.as_view(), name='canned_create'),
    path('settings/canned/<int:pk>/edit/', CannedResponseUpdateView.as_view(), name='canned_edit'),
    path('settings/canned/<int:pk>/delete/', CannedResponseDeleteView.as_view(), name='canned_delete'),
    path('export.csv', TicketExportCsvView.as_view(), name='export_csv'),
    path('filters/save/', SavedTicketFilterCreateView.as_view(), name='filter_save'),
    path('filters/<int:pk>/delete/', SavedTicketFilterDeleteView.as_view(), name='filter_delete'),
    path(
        'filters/<int:pk>/set-default/',
        SavedTicketFilterSetDefaultView.as_view(),
        name='filter_set_default',
    ),
    path('', TicketListView.as_view(), name='list'),
    path('new/', TicketCreateView.as_view(), name='create'),
    path(
        'attachments/<int:pk>/download/',
        TicketAttachmentDownloadView.as_view(),
        name='attachment_download',
    ),
    path('<int:pk>/admin/update/', TicketAdminUpdateView.as_view(), name='admin_update'),
    path('<int:pk>/assign/', TicketAssignView.as_view(), name='assign'),
    path('<int:pk>/comment/', TicketCommentAddView.as_view(), name='comment_add'),
    path('<int:pk>/relations/add/', TicketRelationAddView.as_view(), name='relation_add'),
    path(
        '<int:pk>/relations/<int:relation_pk>/remove/',
        TicketRelationRemoveView.as_view(),
        name='relation_remove',
    ),
    path('<int:pk>/', TicketDetailView.as_view(), name='detail'),
]
