# Generated by Django 5.x

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_canned_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'relation_type',
                    models.CharField(
                        choices=[('related', 'Related'), ('duplicate', 'Duplicate')],
                        default='related',
                        max_length=20,
                    ),
                ),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_relations_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket_high',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='relations_as_high',
                        to='tickets.ticket',
                    ),
                ),
                (
                    'ticket_low',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='relations_as_low',
                        to='tickets.ticket',
                    ),
                ),
            ],
            options={
                'db_table': 'tickets_ticketrelation',
            },
        ),
        migrations.AddIndex(
            model_name='ticketrelation',
            index=models.Index(fields=['ticket_low'], name='tickets_tic_ticket__low_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrelation',
            index=models.Index(fields=['ticket_high'], name='tickets_tic_ticket__high_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketrelation',
            constraint=models.UniqueConstraint(
                fields=('ticket_low', 'ticket_high'),
                name='tickets_ticketrelation_unique_pair',
            ),
        ),
        migrations.AddConstraint(
            model_name='ticketrelation',
            constraint=models.CheckConstraint(
                check=models.Q(('ticket_low_id__lt', models.F('ticket_high_id'))),
                name='tickets_ticketrelation_low_lt_high',
            ),
        ),
    ]
